import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { FormEvent } from "react";
import Task from "./components/Tasks";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const utils = api.useContext();
  const mutation = api.todos.addTask.useMutation({
    onSuccess() {
      utils.todos.getAll.invalidate();
      setText("");
    },
  });

  const [text, setText] = useState("");

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    mutation.mutate(text);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-black">
        <div>
          <h1 className="text-3xl font-bold text-white">Todo</h1>
        </div>
        <form className="space-x-2" onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Enter a todo"
            className="rounded-md p-2"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button className="rounded-md bg-teal-400 p-2">Submit</button>
        </form>
        <div>
          <Task />
        </div>
      </main>
    </>
  );
};

export default Home;
