import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-black">
        <div>
          <h1 className="text-3xl font-bold text-white">Todo</h1>
        </div>
        <form className="space-x-2">
          <input
            type="text"
            placeholder="Enter a todo"
            className="rounded-md p-2"
          />
          <button className="rounded-md bg-teal-400 p-2">Submit</button>
        </form>
        {/* //todo list//  */}
      </main>
    </>
  );
};

export default Home;
