import { type NextPage } from "next";
import Head from "next/head";
import { MouseEventHandler, useState } from "react";
import { FormEvent } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const task = api.todos.getAll.useQuery();

  const utils = api.useContext();
  const mutation = api.todos.addTask.useMutation({
    onSuccess() {
      utils.todos.getAll.invalidate();
    },
  });

  const mutationDelete = api.todos.deleteTask.useMutation({
    onSuccess() {
      utils.todos.getAll.invalidate();
    },
  });

  const [text, setText] = useState("");

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    mutation.mutate(text);
  };

  const handleDelete = (id: string) => {
    mutationDelete.mutate(id);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-black">
        <div>
          <h1 className="text-3xl font-bold text-white">Todo</h1>
        </div>
        <form className="space-x-2" onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Enter a todo"
            className="rounded-md p-2"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button className="rounded-md bg-teal-400 p-2">Submit</button>
        </form>
        {/* //todo list//  */}
        <div className="flex flex-col gap-5 bg-black py-2">
          {task.data
            ? task.data.map((t) => (
                <div className="flex gap-3">
                  <h3 className="text-white" key={t.id}>
                    {t.text}
                  </h3>
                  <button
                    className="rounded-md bg-red-600 p-1 text-white"
                    onClick={() => handleDelete(t.id)}
                  >
                    Delete Task
                  </button>
                </div>
              ))
            : "Add a todo"}
        </div>
      </main>
    </>
  );
};

export default Home;
